project_id = "swtsqngrkkhggjacfhft"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3002"
additional_redirect_urls = [
  "http://localhost:3000",
  "http://localhost:3002",
  "http://localhost:3003"
]

[storage]
enabled = true
